[cosmic-ray]
module-path = "validators.py"
timeout = 50.0
test-command = "env PYTHONPATH=/mnt/c/Users/dhruv/VSCodeProjects/Aegis-Secure/AegisSecure_Backend python -m pytest tests/tests_validators.py"

[cosmic-ray.distributor]
name = "local"

